services:
  - type: web
    name: ramadan-timetable
    runtime: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn ramadan_project.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --worker-class sync --timeout 120
    envVars:
      - key: DJANGO_DEBUG
        value: false
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: ramadan-db
          property: connectionString
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DJANGO_SECURE_SSL_REDIRECT
        value: true
      - key: DJANGO_SESSION_COOKIE_SECURE
        value: true
      - key: DJANGO_CSRF_COOKIE_SECURE
        value: true
      - key: TZ
        value: Asia/Kolkata

databases:
  - name: ramadan-db
    engine: postgres
    plan: starter
    version: "15"
    ipAllowList: []
